development: 
  adapter: mysql2
  encoding: utf8
  database: yard_sale_app_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: 
  adapter: mysql2 
  encoding: utf8 
  reconnect: false 
  database: yard_sale_app_test 
  pool: 5 
  username: root 
  password: 
  socket: /tmp/mysql.sock 