development: 
  adapter: postgresql
  encoding: utf8
  database: yard_sale_app_development
  pool: 5


test: 
  adapter: postgresql 
  encoding: utf8 
  reconnect: false 
  database: yard_sale_app_test 
  pool: 5 
